### ISSUE TITLE
how to change .py to .apk on windows

### ISSUE THREAD

**Issue by Naol-bm** [Asabeneh/30-Days-Of-Python#111]
I don't know but may be using online translator maybe

**Comment by Edith-panda** [comment]
hey! Naol-bm  do one thing set up a virtual box or ubuntu and install buildozer , or  you can even use google collab for it  as well . 
link:  https://towardsdatascience.com/3-ways-to-convert-python-app-into-apk-77f4c9cd55af
Note : it will atleast need 20 gb of free space or more
