### ISSUE TITLE
Repeated print statement in 02_variables_builtin_functions.md

### ISSUE THREAD

**Issue by dhruvp4u** [Asabeneh/30-Days-Of-Python#115]
**Bug:**  In the 'casting' section of 'Checking Data types and Casting', first_name is printed twice.

**Documentation:** 
```python
# str to list
first_name = 'Asabeneh'    
print(first_name)    
print(first_name)                    # 'Asabeneh'    
```

**Fix:** Remove one print statement

**Comment by akashadr** [comment]
Remove one print statement
