### ISSUE TITLE
Day 3 - Exercise 15 - What is the question?

### ISSUE THREAD

**Issue by upthegraph** [Asabeneh/30-Days-Of-Python#232]
Hey Author.
Great job done. No words to thank you.
I am unable to under what are we supposed to do in exercise 15 of day 3. It doesn't ask us to do anything. Can you please look into it.

**Comment by Samuel8275** [comment]
Hi,
I think you need to make an if statement with the not operator, verifying that python and dragon do not have "on".

**Comment by ShantiPoo** [comment]
for below statement I have received output as **False**

_print ('on' not in 'Python' and 'Jargon')_
