### ISSUE TITLE
Error in Examples of Checking Data types and Casting (Day 2)

### ISSUE THREAD

**Issue by JedaiRussia** [Asabeneh/30-Days-Of-Python#297]
# str to int or float
num_str = '10.6'
print('num_int', int(num_str))      # 10

ValueError: invalid literal for int() with base 10: '10.6'

**Comment by engrtobechi** [comment]
_A pull request has already been made in this regard._ 

- The int() function does not accept special characters, hence the reason for the ValueError. 
- To fix this you first need to pass the string object to the float() function and then round it using the int() function. 

**Solution**
`# str to int or float`
`num_str = '10.6'`
`print('num_int', int(float(num_str)))      # 10`
`print('num_float', float(num_str))  # 10.6`

**_Being explicit_**
If you expect a hexadecimal value (which could have special characters), the int() function allows you to explicitly set the base for the string literal. 
Example: 
`num_hex = '8A'`
`print('num_hex', int(num_hex, base=16))`
