### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Jonitich** [Asabeneh/30-Days-Of-Python#340]
Hi, I am not an expert but while doing with debug option the loop
``count = 0
while count < 5:
    if count == 3:
        continue
    print(count)
    count = count + 1``  
on day 10 the explanation says : "The above while loop only prints 0, 1, 2 and 4 (skips 3)." but after continue statement, count always be set to 3, Am I wrong? 
Thanks!

**Comment by sthakur369** [comment]
ya, provided code has a small mistake, we have to add `count = count + 1` before `continue` too, otherwise, the code will be locked in an infinite loop and that's is what happening right now. Here is the correct code

```
count = 0
while count < 5:
  if count == 3:
    count = count + 1
    continue
  print(count)
  count = count + 1
```

**Comment by Jonitich** [comment]
Great to know! Thanks!!
