### ISSUE TITLE
Typo error in Day 5 tutorial

### ISSUE THREAD

**Issue by Satomi-2023** [Asabeneh/30-Days-Of-Python#386]
I found a typographical error in the day 5 tutorial of this repository in the 'Unpacking List Items' section.
1. 
```
lst = ['item','item2','item3', 'item4', 'item5']
```
↓
```
lst = ['item1','item2','item3', 'item4', 'item5']
```
2. 
```
fruits = ['banana', 'orange', 'mango', 'lemon','lime','apple']
first_fruit, second_fruit, third_fruit, *rest = lst
```
↓
```
lst = ['banana', 'orange', 'mango', 'lemon','lime','apple']
first_fruit, second_fruit, third_fruit, *rest = lst
```

**Comment by U-1106** [comment]
@Asabeneh Please kindly review and confirm if I can make fix this and make a pull request. Thank you

**Comment by Satomi-2023** [comment]
Created a pr here: [#397](https://github.com/Asabeneh/30-Days-Of-Python/pull/397)
