### ISSUE TITLE
Typo error in Day 7 tutorial

### ISSUE THREAD

**Issue by Satomi-2023** [Asabeneh/30-Days-Of-Python#387]
I found a typographical error in the day 7 tutorial of this repository in the 'Getting Set's Length' section.
```
# syntax
st = {'item1', 'item2', 'item3', 'item4'}
len(set)    # here
```
↓
```
# syntax
st = {'item1', 'item2', 'item3', 'item4'}
len(st)    # here
```

**Comment by U-1106** [comment]
@Asabeneh Please kindly review and confirm if I can make fix this and make a pull request. Thank you

**Comment by COMMANDO2406** [comment]
Created a pr here: https://github.com/Asabeneh/30-Days-Of-Python/pull/394

**Comment by BlockmasterPlayz** [comment]
Made a pr in #401
