### ISSUE TITLE
day 4_result is not correct

### ISSUE THREAD

**Issue by Galio54** [Asabeneh/30-Days-Of-Python#392]
https://github.com/Asabeneh/30-Days-Of-Python/blame/c8656171d69e79b5dfc743f425991f46b7d1423e/04_Day_Strings/04_strings.md#L331

For this program the result should be 5 for ('y') and 0 for ('th')
challenge = 'thirty days of python'
print(challenge.find('y'))  # 16
print(challenge.find('th')) # 17

**Comment by SokvisalMong** [comment]
I've updated and opened a PR regarding this.
