### ISSUE TITLE
Day 4 - Result for find()

### ISSUE THREAD

**Issue by clara-185** [Asabeneh/30-Days-Of-Python#398]
In lecture:

"find(): Returns the index of the first occurrence of a substring, if not found returns -1
challenge = 'thirty days of python'
print(challenge.find('y'))  # 16
print(challenge.find('th')) # 17
"

But my result is:
print(challenge.find('y'))  # 5
print(challenge.find('th')) # 0

**Comment by SokvisalMong** [comment]
I've updated and opened a PR regarding this. But the second print statement returns 1, not 0.
