### ISSUE TITLE
Day 4- Examples for Escape Sequences in Strings

### ISSUE THREAD

**Issue by clara-185** [Asabeneh/30-Days-Of-Python#399]
In the lecture:
"print('I hope everyone is enjoying the Python Challenge.\nAre you ?') # line break
print('Days\tTopics\tExercises') # adding tab space or 4 spaces 
print('Day 1\t3\t5')
print('Day 2\t3\t5')
print('Day 3\t3\t5')
print('Day 4\t3\t5')
print('This is a backslash  symbol (\\)') # To write a backslash
print('In every programming language it starts with \"Hello, World!\"') # to write a double quote inside a single quote

# output
I hope every one is enjoying the Python Challenge.
Are you ?
Days	Topics	Exercises
Day 1	5	    5
Day 2	6	    20
Day 3	5	    23
Day 4	1	    35
This is a backslash  symbol (\)
In every programming language it starts with "Hello, World!"
"

I don't think the output is correct, it should be:
I hope every one is enjoying the Python Challenge.
Are you ?
Days	Topics	Exercises
Day 1	3	    5
Day 2	3	    5
Day 3	3	    5
Day 4	3	    5
This is a backslash  symbol (\)
In every programming language it starts with "Hello, World!"

Thank you

**Comment by SokvisalMong** [comment]
I've updated and submitted PR addressing this in consistency.
