### ISSUE TITLE
Day 19 file handling

### ISSUE THREAD

**Issue by Eyobagithub** [Asabeneh/30-Days-Of-Python#447]
Import json 
person = {
"name" : "Asabeneh",
"country": "Finland",
"city": "Helsinki",
"skills": ["JavaScript", "React", "Python"]
}
with open("./files/json_example.json', 'w', encoding = 'utf-8') as f:
    json.dump(person, f, ensure_ascii = False, indent = 4)

My Question here is why is it necessary to use "ensure_ascii"?

**Comment by adgan11** [comment]
If you set ensure_ascii to TRUE, then the ascii characters will be dumped in the output as it is.

For example if we created a dictionary like this,
`d ={'lang':'??? ????'} 
  
with open('myfile.json', 'w', encoding ='utf8') as json_file: 
    json.dump(d, json_file, ensure_ascii = False) `

The output will be,
![](https://media.geeksforgeeks.org/wp-content/uploads/20200108182349/python-json.png)

And if it is set to TRUE,
`import json 


# dictionary to be dumped 
d ={'lang':'??? ????'} 

with open('myfile.json', 'w', encoding ='utf8') as json_file: 
	json.dump(d, json_file, ensure_ascii = True) 
`

The output will be,
![](https://media.geeksforgeeks.org/wp-content/uploads/20200108183046/python-json-2.png)

By default it is True, so we have to set it to false.
